---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{id}/posts/{id}/comments":
    get:
      summary: Get all comments
      tags:
      - Comments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: comments found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Comment"
    post:
      summary: Create a comment
      tags:
      - Comments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: comment created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Comment"
  "/api/v1/users/{id}/posts":
    get:
      summary: Get all posts
      tags:
      - Posts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: posts found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Post"
  "/api/v1/users/{id}/posts/{id}":
    get:
      summary: Get post by id
      tags:
      - Posts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: post found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Post"
  "/api/v1/users":
    get:
      summary: Get all users
      tags:
      - Users
      responses:
        '200':
          description: users found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/User"
  "/api/v1/users/{id}":
    get:
      summary: Get user by id
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: user found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
